package com.ibrhalil.forgesys.web;

import com.ibrhalil.forgesys.exception.BusinessException;
import com.ibrhalil.forgesys.exception.ErrorCode;
import com.ibrhalil.forgesys.web.filter.FilterFieldSet;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;

import java.util.Set;

/**
 * Sort whitelist for paged list endpoints. Every list endpoint MUST pass its
 * {@link Pageable} through {@link #require} before querying: without a whitelist a
 * client can order by any resolvable property path (e.g. nested
 * {@code userAccount.tokenInvalidBefore}), which both leaks internal model shape and
 * bypasses the unknown-property {@code PropertyReferenceException} guard (a nested
 * path that <em>exists</em> resolves fine at the repository layer).
 *
 * <p>Whitelist entries are the compile-time String constants generated by the JPA
 * canonical metamodel (e.g. {@code User_.EMAIL}, {@code AuditEntity_.CREATED_DATE}) —
 * renaming an entity field regenerates the constant and breaks the build instead of
 * silently letting a stale property name through. Order-insensitive; a violation maps
 * to 400 {@code validation_error}.
 */
public final class SortGuard {

    private SortGuard() {
    }

    public static void require(Pageable pageable, String... allowedFields) {
        if (!pageable.getSort().isSorted()) {
            return;
        }
        Set<String> allowed = Set.of(allowedFields);
        for (Sort.Order order : pageable.getSort()) {
            if (!allowed.contains(order.getProperty())) {
                throw unsupported(order.getProperty(), allowed);
            }
        }
    }

    public static void require(Pageable pageable, FilterFieldSet fields) {
        if (!pageable.getSort().isSorted()) {
            return;
        }
        for (Sort.Order order : pageable.getSort()) {
            if (!fields.contains(order.getProperty())) {
                throw unsupported(order.getProperty(), fields.names());
            }
        }
    }

    private static BusinessException unsupported(String property, Set<String> allowed) {
        return new BusinessException(ErrorCode.VALIDATION_ERROR,
                "Unsupported sort property: '" + property + "'. Allowed: "
                        + allowed.stream().sorted().toList());
    }
}
