package com.ibrhalil.forgesys.web.filter;

import java.util.Collection;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Whitelist of the filterable/sortable <em>direct</em> attributes of one entity,
 * declared per list feature. Registration uses the compile-time String constants
 * generated by the JPA canonical metamodel (e.g. {@code User_.EMAIL}) so a renamed
 * entity field breaks the build instead of silently opening a stale/absent field.
 * Only direct attributes are ever registered — nested paths (e.g.
 * {@code userAccount.enabled}) are structurally unreachable, which is the defense
 * against filtering through relations or leaking internal fields.
 *
 * <p>The same set doubles as the sort whitelist ({@code SortGuard.require(pageable,
 * fields)}), keeping one source of truth per feature.
 */
public final class FilterFieldSet {

    /** One registered field: wire name, coarse type, and {@code q} search participation. */
    public record RegisteredField(String name, FilterFieldType type, Class<?> javaType, boolean searchable) {
    }

    private final Map<String, RegisteredField> fields;

    private FilterFieldSet(Map<String, RegisteredField> fields) {
        this.fields = Collections.unmodifiableMap(fields);
    }

    public static Builder builder() {
        return new Builder();
    }

    public boolean contains(String name) {
        return fields.containsKey(name);
    }

    /** The registered field, or {@code null} for unknown names (callers map that to 400). */
    public RegisteredField get(String name) {
        return fields.get(name);
    }

    public Set<String> names() {
        return fields.keySet();
    }

    /** Fields participating in the global {@code q} search (OR-CONTAINS over each). */
    public List<RegisteredField> searchableFields() {
        return fields.values().stream().filter(RegisteredField::searchable).toList();
    }

    public static final class Builder {

        private final Map<String, RegisteredField> fields = new LinkedHashMap<>();

        /** Registers a field of a self-describing type (STRING, UUID, BOOLEAN, TEMPORAL). */
        public Builder field(String name, FilterFieldType type, boolean searchable) {
            return register(name, type, type.javaType(), searchable);
        }

        /**
         * Registers an enum-typed field; {@code enumType} is used to parse wire values
         * (unknown names are rejected as 400, not silently unmatched).
         */
        public Builder enumField(String name, Class<?> enumType, boolean searchable) {
            return register(name, FilterFieldType.ENUM, enumType, searchable);
        }

        private Builder register(String name, FilterFieldType type, Class<?> javaType, boolean searchable) {
            if (name == null || name.isBlank()) {
                throw new IllegalArgumentException("Field name must not be blank");
            }
            if (searchable && type != FilterFieldType.STRING) {
                throw new IllegalArgumentException("Searchable fields must be STRING-typed: '" + name + "'");
            }
            fields.put(name, new RegisteredField(name, type, javaType, searchable));
            return this;
        }

        public FilterFieldSet build() {
            return new FilterFieldSet(fields);
        }
    }
}
