package com.ibrhalil.forgesys.web.filter;

import java.util.Collection;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.CriteriaQuery;
import jakarta.persistence.criteria.Expression;
import jakarta.persistence.criteria.JoinType;
import jakarta.persistence.criteria.Root;

/**
 * Whitelist of the filterable/sortable attributes of one list feature, declared per
 * feature. Registration uses the compile-time String constants generated by the JPA
 * canonical metamodel (e.g. {@code User_.EMAIL}) so a renamed entity field breaks the
 * build instead of silently opening a stale/absent field. Only fields declared here
 * are reachable from the wire — the defense against filtering through relations or
 * leaking internal fields; wire names stay flat (never {@code a.b} paths).
 *
 * <p>The same set doubles as the sort whitelist ({@code SortGuard.require(pageable,
 * fields)}), keeping one source of truth per feature.
 *
 * <p>Four registration kinds (K-49):
 * <ul>
 *   <li>{@link FieldKind#DIRECT} — an attribute of the list root entity (wire name
 *       == attribute name), as before;</li>
 *   <li>{@link FieldKind#JOINED} — an attribute of a <em>to-one</em> LEFT JOIN of the
 *       root (e.g. a user's {@code firstName} via {@code userProfile});</li>
 *   <li>{@link FieldKind#SUBQUERY} — a derived scalar (count, name-resolution through
 *       a plain FK column) produced by a {@link SubqueryExpression};</li>
 *   <li>{@link FieldKind#MEMBERSHIP} — collection membership ({@code roleIds IN [...]},
 *       {@code IS_NULL} = empty collection) via EXISTS over a plural association;
 *       filter-only, never sortable, values are member ids.</li>
 * </ul>
 * Flatness rule: JOINED may only target to-one associations and SUBQUERY must stay
 * scalar — a to-many join would multiply rows and silently break paging counts.
 * Collection data goes through SUBQUERY/MEMBERSHIP.
 */
public final class FilterFieldSet {

    /** How a registered field resolves to a query expression. */
    public enum FieldKind {
        DIRECT, JOINED, SUBQUERY, MEMBERSHIP
    }

    /**
     * Subquery-derived scalar expression bound to the list root — counts over plural
     * associations, name-resolution through plain UUID anchor columns, etc. The
     * expression must stay scalar (flat); it is used in WHERE, ORDER BY and SELECT.
     */
    @FunctionalInterface
    public interface SubqueryExpression {

        Expression<?> apply(Root<?> root, CriteriaQuery<?> query, CriteriaBuilder cb);
    }

    /**
     * Collection-membership configuration. Direct form ({@link #direct}) correlates a
     * plural association of the root row; inverse form ({@link #inverse}) exists when
     * the join table is owned by the OTHER side (e.g. a group's members live in
     * {@code User.groups}) — the EXISTS starts from the member entity and correlates
     * through its association back to the root row.
     */
    public record Membership(
            String rootAssociation,
            String memberIdAttribute,
            Class<?> inverseEntity,
            String inverseAssociation,
            String inverseLinkIdAttribute,
            String rootIdAttribute) {

        static Membership direct(String rootAssociation, String memberIdAttribute) {
            return new Membership(rootAssociation, memberIdAttribute, null, null, null, null);
        }

        static Membership inverse(Class<?> inverseEntity, String inverseAssociation,
                String inverseLinkIdAttribute, String rootIdAttribute) {
            return new Membership(null, "id", inverseEntity, inverseAssociation, inverseLinkIdAttribute,
                    rootIdAttribute);
        }

        boolean inverse() {
            return inverseEntity != null;
        }
    }

    /** One registered field: wire name, coarse type, kind and its resolution data. */
    public record RegisteredField(
            String name,
            FilterFieldType type,
            Class<?> javaType,
            boolean searchable,
            FieldKind kind,
            boolean sortable,
            String joinAttribute,
            String leafAttribute,
            SubqueryExpression expression,
            Membership membership) {

        static RegisteredField direct(String name, FilterFieldType type, boolean searchable) {
            return direct(name, type, type.javaType(), searchable);
        }

        static RegisteredField direct(String name, FilterFieldType type, Class<?> javaType, boolean searchable) {
            return new RegisteredField(name, type, javaType, searchable, FieldKind.DIRECT, true,
                    null, null, null, null);
        }

        static RegisteredField joined(String name, FilterFieldType type, boolean searchable,
                String joinAttribute, String leafAttribute) {
            return new RegisteredField(name, type, type.javaType(), searchable, FieldKind.JOINED, true,
                    joinAttribute, leafAttribute, null, null);
        }

        static RegisteredField subquery(String name, FilterFieldType type, boolean searchable,
                SubqueryExpression expression) {
            return new RegisteredField(name, type, type.javaType(), searchable, FieldKind.SUBQUERY, true,
                    null, null, expression, null);
        }

        static RegisteredField membership(String name, Membership membership) {
            return new RegisteredField(name, FilterFieldType.UUID, UUID.class, false, FieldKind.MEMBERSHIP, false,
                    null, null, null, membership);
        }

        /** Operator support is kind-aware: MEMBERSHIP accepts only the set operators. */
        public boolean supports(FilterOperator operator) {
            if (kind == FieldKind.MEMBERSHIP) {
                return operator == FilterOperator.IN || operator == FilterOperator.NOT_IN
                        || operator == FilterOperator.IS_NULL || operator == FilterOperator.IS_NOT_NULL;
            }
            return type.supports(operator);
        }
    }

    private final Map<String, RegisteredField> fields;

    private FilterFieldSet(Map<String, RegisteredField> fields) {
        this.fields = Collections.unmodifiableMap(fields);
    }

    public static Builder builder() {
        return new Builder();
    }

    public boolean contains(String name) {
        return fields.containsKey(name);
    }

    /** The registered field, or {@code null} for unknown names (callers map that to 400). */
    public RegisteredField get(String name) {
        return fields.get(name);
    }

    public Set<String> names() {
        return fields.keySet();
    }

    /** Names registered as sortable — the sort whitelist surface. */
    public List<String> sortableNames() {
        return fields.values().stream().filter(RegisteredField::sortable)
                .map(RegisteredField::name).sorted().toList();
    }

    /** Fields participating in the global {@code q} search (OR-CONTAINS over each). */
    public List<RegisteredField> searchableFields() {
        return fields.values().stream().filter(RegisteredField::searchable).toList();
    }

    /**
     * Resolves a registered field to its query expression against the given root:
     * direct attribute, to-one LEFT JOIN leaf, or subquery scalar. MEMBERSHIP fields
     * have no scalar expression (they resolve to EXISTS predicates in
     * {@link FilterSpecifications}).
     */
    public <T> Expression<?> resolve(String name, Root<T> root, CriteriaQuery<?> query, CriteriaBuilder cb) {
        RegisteredField field = fields.get(name);
        if (field == null) {
            throw new IllegalArgumentException("Unknown field: " + name);
        }
        return switch (field.kind()) {
            case DIRECT -> root.get(field.name());
            case JOINED -> root.join(field.joinAttribute(), JoinType.LEFT).get(field.leafAttribute());
            case SUBQUERY -> field.expression().apply(root, query, cb);
            case MEMBERSHIP -> throw new IllegalArgumentException(
                    "Membership fields resolve to EXISTS predicates, not expressions: " + name);
        };
    }

    public static final class Builder {

        private final Map<String, RegisteredField> fields = new LinkedHashMap<>();

        /** Registers a direct attribute of a self-describing type (STRING, UUID, ...). */
        public Builder field(String name, FilterFieldType type, boolean searchable) {
            return register(RegisteredField.direct(name, type, searchable));
        }

        /**
         * Registers a direct enum-typed field; {@code enumType} is used to parse wire values
         * (unknown names are rejected as 400, not silently unmatched).
         */
        public Builder enumField(String name, Class<?> enumType, boolean searchable) {
            return register(RegisteredField.direct(name, FilterFieldType.ENUM, enumType, searchable));
        }

        /**
         * Registers a field that lives on a to-one association of the root entity
         * (LEFT JOIN + leaf attribute) — e.g. a user's {@code firstName} via the
         * profile. To-many associations are not registrable here by design.
         */
        public Builder joinedField(String name, FilterFieldType type, boolean searchable,
                String joinAttribute, String leafAttribute) {
            return register(RegisteredField.joined(name, type, searchable, joinAttribute, leafAttribute));
        }

        /** Registers a subquery-derived scalar field (counts, referenced names). */
        public Builder subqueryField(String name, FilterFieldType type, boolean searchable,
                SubqueryExpression expression) {
            return register(RegisteredField.subquery(name, type, searchable, expression));
        }

        /**
         * Registers a collection-membership filter over a plural association of the
         * root entity ({@code IN} = contains any of the member ids, {@code IS_NULL} =
         * empty collection). Not sortable, not {@code q}-searchable.
         */
        public Builder membershipField(String name, String memberAssociation, String memberIdAttribute) {
            return register(RegisteredField.membership(name, Membership.direct(memberAssociation, memberIdAttribute)));
        }

        /**
         * Inverse-membership variant for join tables owned by the other side (e.g. a
         * group's members live in {@code User.groups}): the EXISTS starts from
         * {@code inverseEntity}, correlates through {@code inverseAssociation} by link
         * id and filters on the member's own id.
         */
        public Builder inverseMembershipField(String name, Class<?> inverseEntity, String inverseAssociation,
                String inverseLinkIdAttribute, String rootIdAttribute) {
            return register(RegisteredField.membership(name,
                    Membership.inverse(inverseEntity, inverseAssociation, inverseLinkIdAttribute, rootIdAttribute)));
        }

        private Builder register(RegisteredField field) {
            if (field.name() == null || field.name().isBlank()) {
                throw new IllegalArgumentException("Field name must not be blank");
            }
            if (field.searchable() && field.type() != FilterFieldType.STRING) {
                throw new IllegalArgumentException("Searchable fields must be STRING-typed: '" + field.name() + "'");
            }
            fields.put(field.name(), field);
            return this;
        }

        public FilterFieldSet build() {
            return new FilterFieldSet(fields);
        }
    }
}
