spring:
  application:
    name: systemforge
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

systemforge:
  multi-tenancy:
    base-domain: ${BASE_DOMAIN:localhost}
